baseURL: "https://pragathip.github.io/" 
title: Pragathi Praveena
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

params:
    author: Pragathi Praveena
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pragathi Praveena
          subtitle: "I design, build, and evaluate human-robot interfaces to enable remote collaborative work between people. I am currently a Ph.D. candidate in CS at the University of Wisconsin-Madison and I am advised by <mark>[Dr. Bilge Mutlu](http://bilgemutlu.com/)</mark> and <mark>[Dr. Michael Gleicher.](https://gleicher.sites.cs.wisc.edu/)</mark> <br><br> Get a glimpse of my current research in this <mark>[1-minute teaser!](https://twitter.com/HRIPioneers/status/1626663545810354176?s=20)</mark> I am most excited about <mark>[the *Periscope* robotic camera system](https://www.researchgate.net/publication/370602657_Periscope_A_Robotic_Camera_System_to_Support_Remote_Physical_Collaboration)</mark> which facilitates remote collaboration between two people. I have also been exploring the use of <mark>[collaborative robot arms in cinematography.](https://dl.acm.org/doi/10.1145/3544549.3585715)</mark><br><br>**I am on the job market** for post-doc/research scientist/faculty positions! I prototype robotic systems (especially with cobots and cameras) and study user interactions (through mixed methods). I enjoy mentoring and put effort into fostering collective growth. I am deeply passionate about human collaboration, both in my research and outside. "
          imageUrl: "/picture.jpeg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Pragathi Praveena
    socialIcons:
        - name: CV
          url: /praveena-cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=1VSKpsIAAAAJ
        - name: Email
          url: mailto:pragathi@cs.wisc.edu
        - name: LinkedIn
          url: https://www.linkedin.com/in/itispragathi/
        - name: Twitter
          url: https://twitter.com/itispragathi

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Pragathi Praveena"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120â€“155
# * summary: 265
